### ISSUE TITLE
Error blocking Quasar?

### ISSUE THREAD

**Issue by zorg1977** [mancuniancol/script.quasar.1333x-mc#1]
Here is what appears in the logs for version 1.1.0:
< addinfourl at 1515868648 whose fp = < socket._fileobject object at 0x5c7e6db0 > >

**Comment by mancuniancol** [comment]
That is not error

**Comment by mancuniancol** [comment]
I will need access to your log in debug mode. You can share it using pastebin.com

**Comment by zorg1977** [comment]
Here it is: http://pastebin.com/bnbniGf9
I though it may be due to Quasar issue I'm facing: Quasar doesn't play anything neither display the streams popup window (if "choose stream..." selected) even if providers seem to send back torrents.
See for yourself.
Thanks

**Comment by mancuniancol** [comment]
OK, your machine is too slow to handle the number of providers:
[Plugin.video.quasar] 2016-02-11 07:50:23  INFO  AddonSearcher script.quasar.kickass-mc  Provider script.quasar.kickass-mc was too slow. Ignored
You have too options. Or reduce the number of providers or increase your time out. 

I will close this issue, because it is not a problem with the providers and it is a Quasar configuration
